language: python
python:
- 2.7

before_install:
- openssl aes-256-cbc -K $encrypted_8bd7241a878e_key -iv $encrypted_8bd7241a878e_iv
  -in client-secret.json.enc -out client-secret.json -d

install: true

script: true

deploy:
  provider: gae
  keyfile: client-secret.json
  project: bwstreams
