deploy:
  provider: gae
  keyfile: client-secret.json
  project: bwstreams
before_install:
- openssl aes-256-cbc -K $encrypted_8bd7241a878e_key -iv $encrypted_8bd7241a878e_iv
  -in client-secret.json.enc -out client-secret.json -d
