application: bwstreams
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- appstats: on

handlers:
- url: /css
  static_dir: css
- url: /fonts
  static_dir: js
- url: /js
  static_dir: js
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico
  mime_type: image/x-icon
- url: /streams.json
  script: src.app.app
- url: /
  static_files: static/streams.html
  upload: streams.html
- url: /admin/.*
  script: src.app.app
  login: admin

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
